---
CREATE   FUNCTION [dbo].[FN_GetNameConstraintTriggerOnError](@ERROR_STR VARCHAR(MAX))
RETURNS VARCHAR(MAX)
BEGIN
	---
	DECLARE @CONSTRAINT VARCHAR(MAX) = NULL
	---
	IF @ERROR_STR IS NOT NULL BEGIN
		---
		DECLARE @CANT_COMILLAS_SENCILLAS INT = CHARINDEX('''', @ERROR_STR);
		DECLARE @CANT_COMILLAS_DOBLES INT = CHARINDEX('"', @ERROR_STR)
		---
		DECLARE @START INT;
		DECLARE @MIN_COMILLAS INT;

		-- Obtener el mínimo entre comillas sencillas y dobles si ambos son mayores que 0
		IF @CANT_COMILLAS_SENCILLAS > 0 AND @CANT_COMILLAS_DOBLES > 0
		BEGIN
			SET @MIN_COMILLAS = CASE 
								   WHEN @CANT_COMILLAS_SENCILLAS < @CANT_COMILLAS_DOBLES 
								   THEN @CANT_COMILLAS_SENCILLAS 
								   ELSE @CANT_COMILLAS_DOBLES 
								END;
		END
		ELSE IF @CANT_COMILLAS_SENCILLAS > 0
		BEGIN
			SET @MIN_COMILLAS = @CANT_COMILLAS_SENCILLAS;
		END
		ELSE
		BEGIN
			SET @MIN_COMILLAS = @CANT_COMILLAS_DOBLES;
		END;

		-- Asignar el valor resultante a la variable @START
		SET @START = @MIN_COMILLAS;

		---											---													 ---
		DECLARE @END INT = CHARINDEX(IIF(@START = @CANT_COMILLAS_SENCILLAS, '''', '"'), @ERROR_STR, @START + 1)
		---
		SET @CONSTRAINT = IIF(@START > 0 AND @END > 0, 
													  SUBSTRING(@ERROR_STR, @START + 1, @END - @START - 1)
													, @ERROR_STR)
		---
	END
	---
	RETURN @CONSTRAINT
	---	
END