---
CREATE   FUNCTION FN_GET_USER_ZONE_REGION_FORMAT(@USUARIO_ID INT)
RETURNS NVARCHAR(90)
AS
BEGIN
	--
	DECLARE @PAIS_ID INT = (SELECT FkIdPais FROM tblUsuario WHERE Id = @USUARIO_ID)
	--
	DECLARE @RESULT NVARCHAR(90) = (SELECT TIME_ZONE FROM tblPaises WHERE Id = ISNULL(@PAIS_ID, 1))
	--
	RETURN @RESULT
	--
END