CREATE FUNCTION [dbo].[FN_VALIDACION_CONTRAINT_EXISTE_COMUNICADO_tblComunicado](@MENSAJE VARCHAR(500))
RETURNS BIT
AS
BEGIN
	--
	-- VALIDA SI EL MENSAJE ESTA ACTIVO Y SI EXISTE
	DECLARE @RESULT BIT = 1
	DECLARE @MENSAJE_UNICO INT
	--
		BEGIN
	 
		   SET @MENSAJE_UNICO = (SELECT count(*) FROM [tblComunicado] WHERE Mensaje = @MENSAJE) 

		   IF(@MENSAJE_UNICO > 1)
			  BEGIN
				 SET @RESULT = 0
			  END
	
		END
	--
    RETURN(@RESULT)
	--
END