CREATE   FUNCTION [dbo].[FN_VALIDACION_CONTRAINT_ASIGNACION_DEPARTAMENTO_ACTIVO_tblArea_T2_C3](@FK_ID_DEPARTAMENTO INT)
RETURNS BIT
AS
BEGIN
	--
	RETURN (SELECT Activo FROM tblDepartamento WHERE Id = @FK_ID_DEPARTAMENTO)
	--
END