CREATE FUNCTION [dbo].[FN_VALIDACION_CONTRAINT_DESACTIVAR_tblGrupoAgencia](@REACTIVAR BIT, @FK_ID_GRUPO INT)
RETURNS BIT
AS
BEGIN
	--
	-- VALIDA SI EXISTEN RELACIONES ACTIVAS PARA DESACTIVAR UN GRUPO AGENCIA
	DECLARE @RESULT BIT = 1
    DECLARE @CANT INT 
	DECLARE @RELACION_A INT
	--
	IF @REACTIVAR = 0 
	BEGIN

	    SET @RELACION_A = (SELECT count(*) FROM tblAgenciaBancaria WHERE FkIdGrupoAgencia = @FK_ID_GRUPO AND Activo = 1) 

		SET @CANT = @RELACION_A

		SET @RESULT = IIF(@CANT > 0, 0, 1) 
		
	END	
	--
    RETURN(@RESULT)
	--
END